/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlProductos;
import java.awt.Font;

/**
 *
 * @author harri
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Cera una nueva forma de Productos
     */
    public Productos() {
        initComponents();
        tablaProductos.getTableHeader().setFont(new Font("Century Gothic", 1, 14));
        btnEditarPanel.setText("Editar");
        btnEditarPanel.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelRegistrar = new javax.swing.JPanel();
        btnRegistrar = new javax.swing.JLabel();
        separadordeunidades = new javax.swing.JSeparator();
        txtExistencias = new javax.swing.JTextField();
        unidades = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        separadordeprecio = new javax.swing.JSeparator();
        separadordelnombredelproducto = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        nombredelproducto = new javax.swing.JLabel();
        Codigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        separadordecodigo = new javax.swing.JSeparator();
        productos1 = new javax.swing.JLabel();
        btnEditarPanel = new javax.swing.JLabel();
        panelBuscar = new javax.swing.JPanel();
        productos2 = new javax.swing.JLabel();
        separadordeproducto = new javax.swing.JSeparator();
        txtBuscarProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnAddCart = new javax.swing.JLabel();
        btnEditar = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JLabel();
        txtCantidadComprar = new javax.swing.JTextField();
        separadordecodigo1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        labelTitulo.setBackground(new java.awt.Color(153, 153, 153));
        labelTitulo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        labelTitulo.setText("  Productos");
        labelTitulo.setToolTipText("");
        labelTitulo.setOpaque(true);

        panelRegistrar.setBackground(new java.awt.Color(204, 204, 204));
        panelRegistrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegistrar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/resources/savenegro.png"))); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRegistrar.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 50));
        panelRegistrar.add(separadordeunidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 110, 10));

        txtExistencias.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtExistencias.setBorder(null);
        txtExistencias.setOpaque(false);
        panelRegistrar.add(txtExistencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, 110, 30));

        unidades.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        unidades.setText("Existencias");
        panelRegistrar.add(unidades, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, -1, -1));

        precio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        precio.setText("Precio");
        panelRegistrar.add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        txtPrecio.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtPrecio.setBorder(null);
        txtPrecio.setOpaque(false);
        panelRegistrar.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 110, 30));
        panelRegistrar.add(separadordeprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 110, 10));
        panelRegistrar.add(separadordelnombredelproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 190, 10));

        txtNombre.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        panelRegistrar.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 190, 30));

        nombredelproducto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        nombredelproducto.setText("Nombre del producto");
        panelRegistrar.add(nombredelproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        Codigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Codigo.setText("Código");
        panelRegistrar.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtCodigo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCodigo.setBorder(null);
        txtCodigo.setOpaque(false);
        panelRegistrar.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 120, 30));
        panelRegistrar.add(separadordecodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 120, 10));

        productos1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        productos1.setText("Registrar");
        panelRegistrar.add(productos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -5, 70, 40));

        btnEditarPanel.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEditarPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/resources/savenegro.png"))); // NOI18N
        btnEditarPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelRegistrar.add(btnEditarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 100, 50));

        panelBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        productos2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        productos2.setText("Buscar producto");
        panelBuscar.add(productos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 120, 40));
        panelBuscar.add(separadordeproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 250, 10));

        txtBuscarProducto.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtBuscarProducto.setBorder(null);
        txtBuscarProducto.setOpaque(false);
        panelBuscar.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 250, 30));

        jScrollPane1.setBorder(null);

        tablaProductos.setFont(new java.awt.Font("Century Gothic", 0, 13)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre Producto", "Precio", "Existencias"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Float.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.getTableHeader().setResizingAllowed(false);
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tablaProductos);

        panelBuscar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 800, 312));

        btnAddCart.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnAddCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/resources/cart.png"))); // NOI18N
        btnAddCart.setText("Añadir al carro");
        btnAddCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBuscar.add(btnAddCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(608, 10, 140, 40));

        btnEditar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/resources/edit.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBuscar.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 10, 80, 40));

        btnEliminar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/resources/delete.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        panelBuscar.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 10, 90, 40));

        txtCantidadComprar.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        txtCantidadComprar.setBorder(null);
        txtCantidadComprar.setOpaque(false);
        panelBuscar.add(txtCantidadComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 50, 30));
        panelBuscar.add(separadordecodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 50, 10));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel1.setText("Cantidad:");
        panelBuscar.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 7, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    /**
     * coloca los controladores de las acciones
     *
     */
    public void setControlador(ControlProductos c) {
        btnRegistrar.addMouseListener(c);
        btnAddCart.addMouseListener(c);
        btnEditar.addMouseListener(c);
        btnEditarPanel.addMouseListener(c);
        txtBuscarProducto.addKeyListener(c);
        txtCodigo.addKeyListener(c);
        txtNombre.addKeyListener(c);
        txtPrecio.addKeyListener(c);
        txtExistencias.addKeyListener(c);
        btnEliminar.addMouseListener(c);
        tablaProductos.addMouseListener(c);
        txtCantidadComprar.addKeyListener(c);
    }
/**
 * Carga el modo vendedor
 */
    public void cargarModoVendedor() {
        panelRegistrar.setVisible(false);
        panelBuscar.setLocation(panelRegistrar.getLocation());
        panelBuscar.setSize(panelBuscar.getWidth(), this.getWidth() - labelTitulo.getHeight());
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Codigo;
    public javax.swing.JLabel btnAddCart;
    public javax.swing.JLabel btnEditar;
    public javax.swing.JLabel btnEditarPanel;
    public javax.swing.JLabel btnEliminar;
    public javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel nombredelproducto;
    private javax.swing.JPanel panelBuscar;
    public javax.swing.JPanel panelRegistrar;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel productos1;
    private javax.swing.JLabel productos2;
    private javax.swing.JSeparator separadordecodigo;
    private javax.swing.JSeparator separadordecodigo1;
    private javax.swing.JSeparator separadordelnombredelproducto;
    private javax.swing.JSeparator separadordeprecio;
    private javax.swing.JSeparator separadordeproducto;
    private javax.swing.JSeparator separadordeunidades;
    public javax.swing.JTable tablaProductos;
    public javax.swing.JTextField txtBuscarProducto;
    public javax.swing.JTextField txtCantidadComprar;
    public javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtExistencias;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPrecio;
    private javax.swing.JLabel unidades;
    // End of variables declaration//GEN-END:variables

}
